In [2]:
! pip install numpy

In [8]:
import numpy as np
data=np.array([21,23,22,24])
print(data)
print(data[3])
print(type(data))
print(data.shape)

[21 23 22 24]
24
<class 'numpy.ndarray'>
(4,)


In [11]:
data=np.array([[21,22,23],[34,45,35],[67,68,69]])
print(data.shape)
print(data)
print(data[1,1])


(3, 3)
[[21 22 23]
 [34 45 35]
 [67 68 69]]
45


In [12]:
data=data=np.array([[[21,22,23],[34,45,35],[67,68,69] ,[21,22,23],[34,45,35],[67,68,69]]])
print(data.shape)
print(data.size)
print(data.ndim)


(1, 6, 3)
18
3


In [15]:
data=data=np.array([[[[21,22,23],[34,45,35],[67,68,69] ,[21,22,23],[34,45,35],[67,68,69],[21,22,23],[34,45,35],[67,68,69] ,[21,22,23],[34,45,35],[67,68,69]]]])
print(data.shape)
print(data.size)
print(data.ndim)

(1, 1, 12, 3)
36
4
